### ISSUE TITLE
Searches in zooqle plugin don't show more than 30 results

### ISSUE THREAD

**Issue by Pireo** [ArionMiles/Zooqle-qBittorrent-Plugin#3]
Pyhton 2, Windows 7 64 bit ultimate.

**Comment by ArionMiles** [comment]
This is a limitation of Zooqle's Opensearch XML Feeds. They only have the top 30 results in the feeds. I've contacted Zooqle support asking them for a resolution, I'll update on getting a response.

Similarly, ExtraTorrent's RSS Feeds also show only top 50 results, hence if you search with the ExtTorrent search engine in qBitorrent, you get only 50 results.

**Comment by dwilbanks** [comment]
Nope:
Inside the XML you will see 
opensearch:totalResults
by default, they return 30 (at least to my ip address)
You can get additional pages by using &pg=2

**Comment by ArionMiles** [comment]
@dwilbanks appending `&pg=2` to the URL shows the next 30 items (31-60) on the html page, and using the RSS link for that result shows the next 30 items only. the RSS feeds only show the items on the page, which is limited to 30.

**Comment by ArionMiles** [comment]
The number of search results returned has been increased from 30 to 300 in latest build. Unfortunately, we cannot have all the query results displayed in the RSS Feeds using search parameters, @dwilbanks improvised a while loop to return 10 pages worth of results.

**Comment by Pireo** [comment]
@ArionMiles it seems the zooqle plugin, unlike the site behavior, doesn't search in file names.
